### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Untilqis** [Untilqis/protospace-38993#1]
# URL
https://protospace-38993.onrender.com/

**Comment by motomuun** [comment]
@Untilqis さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**プロトタイプ編集機能**

- [ ] **バリデーションによって投稿ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないこと**
空欄のフォームがある状態で「保存する」を押すと、入力済みのフォームの内容も消えてしまいます。消えないように修正をお願いします。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Untilqis** [comment]
修正させていただきます。

**Comment by motomuun** [comment]
@Untilqis さん、再度ご提出頂きありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
